repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: 65ac74a0fd483b19b93293918c088067a9979e6d
    hooks:
      - id: tofu_fmt
      - id: tofu_checkov
      - id: tofu_tflint
      #- id: tofu_trivy
